### ISSUE TITLE
Gracefully fail if localStorage data is corrupted

### ISSUE THREAD

**Issue by ngryman** [jamen/hyperapp-persist#6]
Let's say it's 3:00am, my brain is at 10% of max capacity (basically I'm a 🐒), I introduce a bug that corrupts my state. `hyperapp-persist` saves it, then tries to load it: 💥. I need to reset it manually.

It would be nice to catch potential exceptions from `localStorage.getItem` (and `localStorage.setItem`) and abort the mission if there an exception so the user can go on with his life.

Bonus points: display a friendly warning message that the state is corrupted or send an event?

**Comment by jamen** [comment]
Hey @ngryman, could you clarify what you mean by "corrupted"?

From what I understand, you are concerned with trying to restore some incompatible state?  For example, if the app state updates and all of the users have a different state saved?  Because, this should be handled by a `state.version` field.

By default, if the versions are different, the stored state will be tossed.  But you can provide `opts.rescue` to try and save old versions into the new state.

I could be misunderstanding though, because you mention exceptions from `localStorage`.

**Comment by jamen** [comment]
> You can provide `opts.rescue` to try and save old versions into the new state. Is this not working?

I just realized this wouldn't work how I planned, though.  Because they versions don't stay in sync for all the users.  So trying to restore for a specific version doesn't make sense.

Maybe I could drop `state.version`, but still use the `incompatible(newState, oldState)` function, and then send an event like you suggest.

**Comment by ngryman** [comment]
Suppose that for some reason (I have 🐒 genes), my state becomes `undefined`. The next time I load my state it will violently crash, until I manually open devtools and clear the entry myself.

**Comment by ngryman** [comment]
I've just proposing to handle the *I can't even parse the state*.

**Comment by jamen** [comment]
I believe that should b handled by the `incompatible` function too.  I tried to handle case for primitives, and when types change (e.g., from object to undefined).  It is worth writing tests though, because I can't say for :100: if it covers `undefined`.

**Comment by jamen** [comment]
Oh! I get what you mean now.  It is storing `undefined`. 

I agree that this mixin is a little bit finicky with how the data is stored.  I was thinking, maybe I could clear it after it is restored, so that way you don't get old data bleeding through if something bad happens.

**Comment by jamen** [comment]
So, to sum up what I will do:

 1. Remove `state.version` because this doesn't work with primitive states.
 2. Remove `opts.rescue` and just send an event instead.
 3. Run `removeItem()` after `state.previous` loaded, so it doesn't bleed through

**Comment by ngryman** [comment]
The mixin is just perfect 👍

> maybe I could clear it after it is restored, so that way you don't get the old data bleeding through if something bad happens and the current state can't replace it.

I'm not sure I understand correctly. My initial requirement is that the exception is caught so the rest of the app can run. Then if you find a way to handle this case gracefully, it would be awesome.

**Comment by jamen** [comment]
Yes, my bad, I kind of went off track because I have a few improvements in mind that kind of tie into this issue.  I will do some changes today :)

**Comment by ngryman** [comment]
@jamen No rush though, thanks mate!

**Comment by jamen** [comment]
@ngryman Does `hyperapp-persist@2.0.0` fix this?
